/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":maelstrom-node"))
}

application {
    // Define the main class for the application.
    mainClass = "win.huggw.app.AppKt"
}
